"""add_message_delivery_status

Revision ID: 0f34624a8c5c
Revises: fa878e124ea5
Create Date: 2025-11-16 22:49:04.319454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f34624a8c5c'
down_revision = 'fa878e124ea5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_read_receipts', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_read_receipts', 'delivered_at')
    # ### end Alembic commands ###
